# This is for internal use to make sure our samples follow best practices. You can delete this in your fork.
name: Template Validation Sample Workflow
on: 
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation_job:
    runs-on: ubuntu-latest
    name: template validation
    steps:
      - uses: actions/checkout@v4

      - uses: microsoft/template-validation-action@v0.3.2
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # project specific (matches main.parameters.json)
          AZURE_OPENAI_SERVICE: ${{ vars.AZURE_OPENAI_SERVICE }}
          AZURE_OPENAI_SERVICE_LOCATION: ${{ vars.AZURE_OPENAI_SERVICE_LOCATION }}
          AZURE_OPENAI_RESOURCE_GROUP: ${{ vars.AZURE_OPENAI_RESOURCE_GROUP }}
          AZURE_OPENAI_REUSE_EXISTING: ${{ vars.AZURE_OPENAI_REUSE_EXISTING }}
          AZURE_OPENAI_ENDPOINT: ${{ vars.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_REALTIME_DEPLOYMENT: ${{ vars.AZURE_OPENAI_REALTIME_DEPLOYMENT }}
          AZURE_OPENAI_REALTIME_DEPLOYMENT_CAPACITY: ${{ vars.AZURE_OPENAI_REALTIME_DEPLOYMENT_CAPACITY }}
          AZURE_OPENAI_REALTIME_DEPLOYMENT_VERSION: ${{ vars.AZURE_OPENAI_REALTIME_DEPLOYMENT_VERSION }}
          AZURE_OPENAI_EMB_DEPLOYMENT_CAPACITY: ${{ vars.AZURE_OPENAI_EMB_DEPLOYMENT_CAPACITY }}
          AZURE_OPENAI_EMB_DIMENSIONS: ${{ vars.AZURE_OPENAI_EMB_DIMENSIONS }}
          AZURE_SEARCH_INDEX: ${{ vars.AZURE_SEARCH_INDEX }}
          AZURE_SEARCH_SEMANTIC_CONFIGURATION: ${{ vars.AZURE_SEARCH_SEMANTIC_CONFIGURATION }}
          AZURE_SEARCH_IDENTIFIER_FIELD: ${{ vars.AZURE_SEARCH_IDENTIFIER_FIELD }}
          AZURE_SEARCH_CONTENT_FIELD: ${{ vars.AZURE_SEARCH_CONTENT_FIELD }}
          AZURE_SEARCH_TITLE_FIELD: ${{ vars.AZURE_SEARCH_TITLE_FIELD }}
          AZURE_SEARCH_EMBEDDING_FIELD: ${{ vars.AZURE_SEARCH_EMBEDDING_FIELD }}
          AZURE_SEARCH_USE_VECTOR_QUERY: ${{ vars.AZURE_SEARCH_USE_VECTOR_QUERY }}
          AZURE_SEARCH_SERVICE: ${{ vars.AZURE_SEARCH_SERVICE }}
          AZURE_SEARCH_SERVICE_RESOURCE_GROUP: ${{ vars.AZURE_SEARCH_SERVICE_RESOURCE_GROUP }}
          AZURE_SEARCH_SERVICE_LOCATION: ${{ vars.AZURE_SEARCH_SERVICE_LOCATION }}
          AZURE_SEARCH_SERVICE_SKU: ${{ vars.AZURE_SEARCH_SERVICE_SKU }}
          AZURE_SEARCH_SEMANTIC_RANKER: ${{ vars.AZURE_SEARCH_SEMANTIC_RANKER }}
          AZURE_SEARCH_REUSE_EXISTING: ${{ vars.AZURE_SEARCH_REUSE_EXISTING }}
          AZURE_SEARCH_ENDPOINT: ${{ vars.AZURE_SEARCH_ENDPOINT }}
          AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_RESOURCE_GROUP: ${{ vars.AZURE_STORAGE_RESOURCE_GROUP }}
          AZURE_STORAGE_SKU: ${{ vars.AZURE_STORAGE_SKU }}
          AZURE_CONTAINER_APP_NAME: ${{ vars.AZURE_CONTAINER_APP_NAME }}
          AZURE_CONTAINER_APPS_WORKLOAD_PROFILE: ${{ vars.AZURE_CONTAINER_APPS_WORKLOAD_PROFILE }}
          AZURE_LOG_ANALYTICS: ${{ vars.AZURE_LOG_ANALYTICS }}
      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
